### ISSUE TITLE
Not able to get callback to my application after clicking on Accept button on permission screen

### ISSUE THREAD

**Issue by amityadav1312** [microsoftgraph/android-java-connect-sample#7] opened 2017-01-09 12:33 UTC
I am Not able to get callback to my application after clicking on Accept button on permission screen. All working fine on all devices except Samsung S6 and Samsung J5 devices having Android version 6.0.1.
I have tried all options but couldn't succeed. Please help me out if having any solution.

**Comment by DianeD** [comment] 2017-01-11 21:51
Hi @amityadav1312 . Thanks for reporting this issue. We’re looking into it.

**Comment by amityadav1312** [comment] 2017-01-13 09:19
Hello @DianeD ,
Any update on this issue? Are we able to resolve this issue.

**Comment by DianeD** [comment] 2017-01-13 21:15
Hi @amityadav1312 . Sorry, not yet. We’re investigating whether to replace the auth library used in this sample. 

It looks like there’s an issue where it might work for only one app on one device. Someone would have to register an intent in Android that intercepts the replyURI no matter the initiator of the request. All responses would go to the one app, or can’t find its way back to the app either because the intent isn’t there or they made more than one sample app and have both installed.

**Comment by amityadav1312** [comment] 2017-01-14 15:05
Hi @DianeD ,
Thanks a lot for reply, I think this would help you to debug more deeply. I am using only one app on one device. Same application is working on other devices of samsung and nexus, except Samsung S6, S7, J5 and high end devices even though the chrome version on all devices are same just difference in the Android version these devices having Android version 6.0.1. Also if i set Action Button using setActionButton method for customTabs it's not working.
Thanks
Amit Kumar

**Comment by amityadav1312** [comment] 2017-01-17 09:18
Hi @DianeD ,
Did you get any workaround? Actually I have to integrate this sample project to my Project, But its not working for Samsung device as I have mentioned above. Please let me know if you are updating the same for this issue.
Thanks
Amit Kumar

**Comment by DianeD** [comment] 2017-01-17 23:44
Hi @amityadav1312 . Status update: We downloaded the sample and ran it successfully on Samsung Galaxy S7 and J7 devices that are using Android 6.0.1. We tested with both personal and work accounts. 

We'll continue to test around this to try to consistently reproduce the issue you're seeing. A couple times, the app hung after clicking **Accept** in the consent screen--once when the wrong password was entered and once with a particular setup for two-factor auth.

**Comment by DianeD** [comment] 2017-01-23 22:44
Hi @amityadav1312 . In general, the sample is working on the S7 and J7 devices we tested. The S7 did get into a state where the login window didn't close after sign in/consent, so the auth didn't complete. I reset to the default device settings and it worked again. Are you still experiencing problems?

**Comment by amityadav1312** [comment] 2017-01-25 09:04
Hi @DianeD  I am still getting the same issue which you talked about. Would you please let me know the what device setting did you reset to working it fine.
Thanks

**Comment by DianeD** [comment] 2017-01-25 15:23
I used Backup and reset > Factory data reset. Does your login window remain open after clicking Accept?
Can you capture your network calls that lead up to this?

**Comment by amityadav1312** [comment] 2017-01-26 08:50
yes my widow remains open after accept button click...

**Comment by amityadav1312** [comment] 2017-01-27 05:08
Hello @DianeD , Actually I am using this module in my project and which is supposed to go live in some days. So I desperately need a fix of this problem. As you mentioned earlier that when you did factory reset its working fine. But we can't ask our clients to factory reset its phone. So please if its possible to debug and fix the issue, it would be a great help for me. I would be great thankful to you if you would look in this issue fix it. Hoping a reply from you side your side.
Thanks
Amit Kumar

**Comment by DianeD** [comment] 2017-01-27 16:15
Hi @amityadav1312 . Sorry, I did that to start from scratch to try to repro again. I thought it might be related to changing some developer options. Still looking into it.

**Comment by DianeD** [comment] 2017-01-28 00:14
Hi @amityadav1312 . We plan to update this sample so that it uses the [recommended auth library](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-libraries#compatible-client-libraries) for Android apps: [OIDCAndroidLib](https://github.com/kalemontes/OIDCAndroidLib). We suggest you use OIDCAndroidLib too. The Azure team has a [Native app sample](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-devquickstarts-android) that shows how to use it.

FWIW, it looks like another user of the current auth library is experiencing a [similar issue](https://github.com/openid/AppAuth-Android/issues/157) to what you're seeing.

**Comment by amityadav1312** [comment] 2017-01-30 11:42
Hi @DianeD , Thanks a lot for your reply and suggestion. I have started integrating the suggested library to my project. But in the mean time I just wanted to know, if you are planning to fix the issue and release it. I am asking this, because I have implemented you library thoroughly in my project and it will take lots of time and effort to replace you library with the suggested one. Please confirm if you have decided any expected date to fix this issue.
Thanks a lot again...
Amit Kumar

**Comment by DianeD** [comment] 2017-01-30 23:11
Hi Amit. To clarify: The [Microsoft Graph SDK for Android](https://github.com/microsoftgraph/msgraph-sdk-android) does not have a hard dependency on any particular auth library. Because the failure you're seeing happens before the SDK is ever called, the changes we're planning for the sample should not affect using the SDK at all. 

We think that the current auth library might be causing the [login issue](https://github.com/openid/AppAuth-Android/issues/157).

**Comment by iainmcgin** [comment] 2017-01-31 00:44
Lead maintainer for AppAuth here - anything I can do to help?

**Comment by iainmcgin** [comment] 2017-01-31 00:46
There is a known issue with the custom tab implementation Samsung SBrowser:

https://github.com/openid/AppAuth-Android/issues/116

It's possible that older Samsung phones are pinned to a version of the browser that hasn't received a fix for that issue. You can blacklist SBrowser custom tabs in AppAuth, or blacklist custom tab usage generally.

**Comment by DianeD** [comment] 2017-02-24 21:42
Hi @amityadav1312 . Closing this issue. Please reopen if you're still having problems.
Thanks @iainmcgin for jumping in!

**Closed as completed by DianeD** 2017-02-24 21:42 UTC
